name: Verify PR

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'LICENSE'
      - '**/.gitignore'
      - '**.md'
      - '**.adoc'
      - '*.txt'
      - '*.py'
      - '.github/*'
      - 'Jenkinsfile*'
      - '.jenkins/**'
  
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 120
    strategy:
      matrix:
        os: [ubuntu-latest]
        java-version: [11]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Run launch.sh
    steps:
      - name: Disk space report before modification
        shell: bash
        run: |
          echo "Available storage:"
          df -h
      # Inspired to maximize-build-space action https://github.com/easimon/maximize-build-space
      - name: Free disk space (remove dotnet, android and haskell)
        shell: bash
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
      - name: Disk space report after modification
        shell: bash
        run: |
          echo "Available storage:"
          df -h
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
      # See https://docs.github.com/en/actions/guides/building-and-testing-java-with-maven#caching-dependencies
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Verify Launch Script
        shell: bash
        run: |
          timeout 5m ./launch.sh clean install -Popenshift
